[package]
name = "pcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#sleigh = { path="sleigh" }
sleigh = { git="https://github.com/Molkars/sleigh" }

[workspace]
members = []
