workspace = { members = ["sleigh-sys"] }
[package]
name = "pcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "setup"
path = "setup.rs"

[dependencies]
sleigh = "*"

[patch.crates-io]
sleigh-sys = { path = "sleigh-sys" }
